### ISSUE TITLE
Compliance results no longer reports back to Chef Compliance with latest version of inspec

### ISSUE THREAD

**Issue by yvovandoorn** [chef-cookbooks/audit#41]
### Cookbook version
0.6.0

### Chef-client version
12.9.41

### Inspec version
0.21.0

### Platform Details
Windows 2012 R2 (Azure)

### Scenario:
Running audit cookbook with Windows specific profile to report back into Compliance

### Steps to Reproduce:
Install inspec 0.21.0
You get 0 results reported back to Compliance

### Expected Result:
Compliant / Issues reporting back into Compliance dashboard

### Actual Result:
```
2016-05-12_17:13:43.76370 17:13:43.763 DEB => owner: &shared.Owner{PasswordHash:"", Login:"unit4", Name:"unit4", IsOrg:true, Source:sql.NullString{String:"9cf58bf8-a53b-4bf9-58fe-2f493bf4adfc", Valid:true}, UUID:uuid.UUID{ID:"2a50ead3-2918-41a6-5915-48f45a41b74f"}}
2016-05-12_17:13:43.76466 17:13:43.764 ERR => DB error: sql: no rows in result set
2016-05-12_17:13:43.76908 17:13:43.769 ERR => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Couldn't find rule  in profile unit4/identity-server-level-1
2016-05-12_17:13:43.76923 17:13:43.769 ERR => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Couldn't find rule  in profile unit4/identity-server-level-1
2016-05-12_17:13:43.76934 17:13:43.769 ERR => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Couldn't find rule  in profile unit4/identity-server-level-1
2016-05-12_17:13:43.76944 17:13:43.769 ERR => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Couldn't find rule  in profile unit4/identity-server-level-1
2016-05-12_17:13:43.76954 17:13:43.769 ERR => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Couldn't find rule  in profile unit4/identity-server-level-1
```

```
2016-05-12_17:13:43.76975 17:13:43.769 DEB => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] Add scan result for 2a50ead3-2918-41a6-5915-48f45a41b74f/732b4772-0122-4ec8-468f-ce4bc706f254/937ab0a4-2f99-4ccc-4d74-8809956ec7dd:0 with unit4/identity-server-level-1
2016-05-12_17:13:43.76989 17:13:43.769 INF => [2a50ead3-2918-41a6-5915-48f45a41b74f/a9df344b-5c01-4359-50ff-5016064a2c8f] scan result | 0 | 0 | 0 | 0 | 0 | packages | 0 | 0 | 0 | 0 | 0 |
```

**Comment by chris-rock** [comment]
Thanks yvo, that is not restricted to windows. We changed the default json formatter that is used in audit cookbook with version https://github.com/chef/inspec/tree/v0.21.0 This was marked as a breaking change :-) We should have pinned that until the new Chef Compliance arrives.

**Comment by chris-rock** [comment]
Pinning InSpec to ` 0.20.1` should fix that problem until a new Chef Compliance release is out.

**Comment by sclark007** [comment]
@chris-rock i still see issues with this. 


[root@statvprchefcomp01 ~]# rpm -qa | grep chef
chef-compliance-1.2.3-1.el6.x86_64
chef-12.5.1-1.el6.x86_64

wrapper cookbook attributes:
default['audit']['inspec_version'] = '0.22.0'
default['audit']['profiles']['base/ssh'] = true

Chef-client 
chef-12.9.38-1.el7.x86_64

[root@stlabvdv001 ~]# chef-client -o neustar-audit
Starting Chef Client, version 12.9.38
resolving cookbooks for run list: ["neustar-audit"]
Synchronizing Cookbooks:
  - audit (0.7.0)
  - neustar-audit (1.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: audit::default
  * compliance_profile[ssh] action fetch
    * chef_gem[inspec] action install
      - install version 0.22.0 of package inspec
    - install/update inspec
    * directory[/var/chef/cache/compliance] action create (up to date)
    - fetch compliance profile
    * chef_gem[inspec] action install (up to date)
    * directory[/var/chef/cache/compliance] action create (up to date)
  
  * compliance_profile[ssh] action execute
    * chef_gem[inspec] action install (up to date)
    - install/update inspec.F..FF.FFFFFFFFFFF..........F..F.FF.FFFFF.FFFFF.F.FF..FFFFFFFF.F....F

Failures:

  1) SSH Configuration AddressFamily should match /inet|any/
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match /inet|any/
     # base/ssh/controls/ssh_spec.rb:32:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  2) SSH Configuration BatchMode should eq "no"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "no"
            got: nil

       (compared using ==)
     # base/ssh/controls/ssh_spec.rb:67:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  3) SSH Configuration CheckHostIP should eq "yes"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "yes"
            got: nil

       (compared using ==)
     # base/ssh/controls/ssh_spec.rb:79:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  4) SSH Configuration Ciphers should match "aes256-ctr,aes192-ctr,aes128-ctr"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match "aes256-ctr,aes192-ctr,aes128-ctr"
     # base/ssh/controls/ssh_spec.rb:103:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  5) SSH Configuration MACs should match "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
     # base/ssh/controls/ssh_spec.rb:115:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  6) SSH Configuration KexAlgorithms should match "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
     # base/ssh/controls/ssh_spec.rb:127:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  7) SSH Configuration ForwardAgent should eq "no"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "no"
            got: nil

       (compared using ==)
     # base/ssh/controls/ssh_spec.rb:139:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  8) SSH Configuration ForwardX11 should eq "no"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "no"
            got: nil

       (compared using ==)
     # base/ssh/controls/ssh_spec.rb:151:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  9) SSH Configuration HostbasedAuthentication should eq "no"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "no"
            got: nil

       (compared using ==)
     # base/ssh/controls/ssh_spec.rb:163:in `block (3 levels) in load'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
     # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
     # (eval):2:in `block in action_execute'
     # (eval):2:in `action_execute'

  10) SSH Configuration RhostsRSAAuthentication should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/ssh_spec.rb:175:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  11) SSH Configuration RSAAuthentication should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: nil

        (compared using ==)
      # base/ssh/controls/ssh_spec.rb:186:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  12) SSH Configuration PasswordAuthentication should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/ssh_spec.rb:199:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  13) SSH Configuration Tunnel should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/ssh_spec.rb:210:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  14) SSH Configuration PermitLocalCommand should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/ssh_spec.rb:221:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  15) SSH Configuration AddressFamily should match /inet|any/
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected nil to match /inet|any/
      # base/ssh/controls/sshd_spec.rb:108:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  16) SSH Configuration ListenAddress should not eq nil
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: value != nil
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:123:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  17) SSH Configuration StrictModes should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:147:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  18) SSH Configuration LogLevel should match /VERBOSE|DEBUG/
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected "INFO" to match /VERBOSE|DEBUG/
        Diff:
        @@ -1,2 +1,2 @@
        -/VERBOSE|DEBUG/
        +"INFO"
      # base/ssh/controls/sshd_spec.rb:159:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  19) SSH Configuration Ciphers should eq "aes256-ctr,aes192-ctr,aes128-ctr"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "aes256-ctr,aes192-ctr,aes128-ctr"
             got: "aes128-ctr,aes192-ctr,aes256-ctr"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:183:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  20) SSH Configuration MACs should eq "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:195:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  21) SSH Configuration KexAlgorithms should eq "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:207:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  22) SSH Configuration UseLogin should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:218:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  23) SSH Configuration UsePrivilegeSeparation should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: "no"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:231:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  24) SSH Configuration LoginGraceTime should eq "30s"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "30s"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:254:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  25) SSH Configuration MaxAuthTries should eq "2"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "2"
             got: "4"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:266:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  26) SSH Configuration MaxSessions should eq "10"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "10"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:278:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  27) SSH Configuration MaxStartups should eq "10:30:100"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "10:30:100"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:290:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  28) SSH Configuration PubkeyAuthentication should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:303:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  29) SSH Configuration IgnoreUserKnownHosts should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:327:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  30) SSH Configuration UsePAM should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: "yes"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:350:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  31) SSH Configuration PasswordAuthentication should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: "yes"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:361:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  32) SSH Configuration KerberosOrLocalPasswd should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:396:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  33) SSH Configuration TCPKeepAlive should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:408:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  34) SSH Configuration ClientAliveInterval should eq "600"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "600"
             got: "300"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:420:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  35) SSH Configuration ClientAliveCountMax should eq "3"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "3"
             got: "0"

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:432:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  36) SSH Configuration PermitTunnel should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:443:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  37) SSH Configuration AllowTcpForwarding should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:455:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  38) SSH Configuration AllowAgentForwarding should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:467:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  39) SSH Configuration GatewayPorts should eq "no"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "no"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:479:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  40) SSH Configuration X11UseLocalhost should eq "yes"
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

        expected: "yes"
             got: nil

        (compared using ==)
      # base/ssh/controls/sshd_spec.rb:503:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

  41) File /etc/ssh should not be readable by others
      Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
        expected File /etc/ssh not to be readable by others
      # base/ssh/controls/ssh_folder_spec.rb:50:in `block (3 levels) in load'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:113:in `block (2 levels) in <class:ComplianceProfile>'
      # /var/chef/cache/cookbooks/audit/libraries/profile.rb:94:in `block in <class:ComplianceProfile>'
      # (eval):2:in `block in action_execute'
      # (eval):2:in `action_execute'

Finished in 0.18642 seconds (files took 0.96672 seconds to load)
69 examples, 41 failures

Failed examples:

rspec  # SSH Configuration AddressFamily should match /inet|any/
rspec  # SSH Configuration BatchMode should eq "no"
rspec  # SSH Configuration CheckHostIP should eq "yes"
rspec  # SSH Configuration Ciphers should match "aes256-ctr,aes192-ctr,aes128-ctr"
rspec  # SSH Configuration MACs should match "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
rspec  # SSH Configuration KexAlgorithms should match "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
rspec  # SSH Configuration ForwardAgent should eq "no"
rspec  # SSH Configuration ForwardX11 should eq "no"
rspec  # SSH Configuration HostbasedAuthentication should eq "no"
rspec  # SSH Configuration RhostsRSAAuthentication should eq "no"
rspec  # SSH Configuration RSAAuthentication should eq "yes"
rspec  # SSH Configuration PasswordAuthentication should eq "no"
rspec  # SSH Configuration Tunnel should eq "no"
rspec  # SSH Configuration PermitLocalCommand should eq "no"
rspec  # SSH Configuration AddressFamily should match /inet|any/
rspec  # SSH Configuration ListenAddress should not eq nil
rspec  # SSH Configuration StrictModes should eq "yes"
rspec  # SSH Configuration LogLevel should match /VERBOSE|DEBUG/
rspec  # SSH Configuration Ciphers should eq "aes256-ctr,aes192-ctr,aes128-ctr"
rspec  # SSH Configuration MACs should eq "hmac-sha2-512,hmac-sha2-256,hmac-ripemd160"
rspec  # SSH Configuration KexAlgorithms should eq "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1"
rspec  # SSH Configuration UseLogin should eq "no"
rspec  # SSH Configuration UsePrivilegeSeparation should eq "yes"
rspec  # SSH Configuration LoginGraceTime should eq "30s"
rspec  # SSH Configuration MaxAuthTries should eq "2"
rspec  # SSH Configuration MaxSessions should eq "10"
rspec  # SSH Configuration MaxStartups should eq "10:30:100"
rspec  # SSH Configuration PubkeyAuthentication should eq "yes"
rspec  # SSH Configuration IgnoreUserKnownHosts should eq "yes"
rspec  # SSH Configuration UsePAM should eq "no"
rspec  # SSH Configuration PasswordAuthentication should eq "no"
rspec  # SSH Configuration KerberosOrLocalPasswd should eq "no"
rspec  # SSH Configuration TCPKeepAlive should eq "no"
rspec  # SSH Configuration ClientAliveInterval should eq "600"
rspec  # SSH Configuration ClientAliveCountMax should eq "3"
rspec  # SSH Configuration PermitTunnel should eq "no"
rspec  # SSH Configuration AllowTcpForwarding should eq "no"
rspec  # SSH Configuration AllowAgentForwarding should eq "no"
rspec  # SSH Configuration GatewayPorts should eq "no"
rspec  # SSH Configuration X11UseLocalhost should eq "yes"
rspec  # File /etc/ssh should not be readable by others


    - execute compliance profile
    * chef_gem[inspec] action install (up to date)
    * file[/var/chef/cache/compliance/base_ssh_report.json] action create
      - update content in file /var/chef/cache/compliance/base_ssh_report.json from 710f33 to 3bb01f
      - suppressed sensitive resource
      - restore selinux security context
  
  * compliance_report[chef-server] action execute
    - report compliance profiles' results

Running handlers:
Running handlers complete
Chef Client finished, 5/10 resources updated in 17 seconds

**Comment by chris-rock** [comment]
This is fixed with the latest versions. Also we added a matrix that shows the compatibility: https://github.com/chef-cookbooks/audit#chef-compliance-and-inspec

**Comment by sonykphilip** [comment]
dd

**Comment by sonykphilip** [comment]
Still facing this problem with the latest Chef Compliance and Inspec. Once the scan is completed, it does not list the rows in the browser when you click on the machine name. However, if you do a 'sudo chef-compliance-ctl restart core', the page then lists the rows. Rinse and repeat on the next scan.

OS: Red Hat Enterprise Linux Server release 7.2 (Maipo) 64-bit

RPMs Installed: chef-compliance-1.7.7-1.el7.x86_64.rpm, inspec-1.14.1-1.el7.x86_64.rpm

$ inspec -v
1.14.1

==> /var/log/chef-compliance/core/current <==
2017-02-23_04:19:32.50753 04:19:32.507 ERR => DB error: sql: no rows in result set
2017-02-23_04:19:32.50794 04:19:32.507 DEB => ID of user admin changed: b31f7a6d-22a1-4649-6e04-cdf59eb2c3a7 -> 696fe0a3-d9d3-4da9-bd20-4eae7b1676fb (resetting)
2017-02-23_04:19:32.50794 04:19:32.507 DEB => Authenticated user: &{PasswordHash: Login:compliance Name:Foo Bar Admin IsOrg:false Source:{String: Valid:false} UUID:{ID:b31f7a6d-22a1-4649-6e04-cdf59eb2c3a7}}
2017-02-23_04:19:32.50827 04:19:32.508 ERR => DB error: sql: no rows in result set
2017-02-23_04:19:32.50894 [GIN] 2017/02/23 - 04:19:32 | 200 |    2.268823ms | 192.168.166.236 |   GET     /owners/b31f7a6d-22a1-4649-6e04-cdf59eb2c3a7/scans/151f9220-06c7-49d9-6879-12bd38b712bd

**Comment by chris-rock** [comment]
@sonykphilip Seems like you are not using the audit cookbook. Could you please place your question in https://www.chef.io/support/ then?
